### ISSUE TITLE
Randomized characters as a per language setting

### ISSUE THREAD

**Issue by zacdemon** [mclemente/fvtt-module-polyglot#283]
**Is your feature request related to a problem? Please describe.**
Right now, whether characters are randomized or not is a system wide setting that effects every single language. This is fine usually but certain fonts (Phyrexian in my case) require a particular ordering of characters at the beginning and ending to make the sentence look like it should.

**Describe the solution you'd like**
If how characters are randomized was a per language setting instead of system wide, I could set a particular language (Phyrexian) to use no randomization and setup my sentences to look correct without it affecting every other language in the system.

**Describe alternatives you've considered**
If there was some way to set certain characters in a language to not appear randomly so that I could position those characters where they need to be and let the rest of the sentence be random, but this seems far more complicated.

**Additional context**
![image](https://user-images.githubusercontent.com/22028379/225191031-80468084-8220-4e39-a4bd-90eee4716b16.png)
![image](https://user-images.githubusercontent.com/22028379/225191125-75171823-3247-4537-acd5-5ce8ab7c78d2.png)

**Comment by mclemente** [comment]
That's a good idea. The whole Languages settings could use a lot of improvements. Like setting a language to be 26-letters long (e.g. fonts with no numbers) or the logographical fonts, since those are hard-coded currently.
My main issue is how to apply those changes without negatively affecting any of the current users (e.g. avoid the "update 5 minutes before the session and it broke my languages" issues). The other issue is to change the current menu to be less busy with those changes.
