### ISSUE TITLE
[Feature Request] Add non alphanumeric to certain languages

### ISSUE THREAD

**Issue by Darrel-Santoso** [mclemente/fvtt-module-polyglot#341]
**Is your feature request related to a problem? Please describe.**
My Pf2e character is from Tien and I would like to use the Korean and Japanese language equivalent. The DM told me that Korean is Hwan and Japanese is Minkaian. Using the plugin reveals that the symbols used aren't similar to Korean Hangeul or Japanese Kanji.

**Describe the solution you'd like**
Korean Hangeul be used for characters when speaking in Hwan or Japanese Kanji when speaking in Minkaian.

**Describe alternatives you've considered**
Katakana and Hiragana for Minkaian.

**Additional context**
Currently Hwan looks like this:
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/79248128/b56424af-7dd0-4aec-ba0c-67935959395e)
And Minkaian looks like this:
![image](https://github.com/mclemente/fvtt-module-polyglot/assets/79248128/95ed32bb-53eb-40b2-a459-f898b696c14d)

**Comment by mclemente** [comment]
Early in PF2e's life I've added the original CRB languages since they were pretty similar to dnd5e's, but I haven't and won't keep up with updating them.

There is a Kanji-like font within Polyglot, it's "Oriental". Ask your GM to change the language's font.

As for Korean, I couldn't find any free font that simulates Hangeul in a convincing way, and Google's Korean font's file size is way 4 times bigger than all the other fonts included in the project, so I that's no-go too.

It is also possible for your GM to add their own fonts, you just have to find the proper font and upload it to Foundry (that's a core feature, not Polyglot's btw).
